# Generated by Django 6.0.2 on 2026-02-07 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birth_data',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
    ]
