# Generated by Django 6.0.2 on 2026-02-07 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_notes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chapters',
            options={'ordering': ['name'], 'verbose_name': 'Глава', 'verbose_name_plural': 'Главы'},
        ),
        migrations.AlterModelOptions(
            name='sections',
            options={'ordering': ['name'], 'verbose_name': 'Раздел', 'verbose_name_plural': 'Разделы'},
        ),
    ]
