# Generated by Django 6.0.2 on 2026-02-26 08:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_notes', '0002_alter_chapters_options_alter_sections_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('query', models.TextField(verbose_name='Запрос пользователя')),
                ('response', models.TextField(blank=True, null=True, verbose_name='Ответ ИИ')),
                ('model_AI', models.CharField(default='deepseek-ai/DeepSeek-R1-0528', verbose_name='Модель ИИ')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Дата запроса')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Сообщения чата',
                'verbose_name_plural': 'Сообщении чата',
                'ordering': ['-time_create'],
            },
        ),
    ]
