# Generated by Django 6.0.2 on 2026-02-27 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_notes', '0003_chatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='prompt',
            field=models.CharField(default='Художественный писатель с богатым стилем', verbose_name='Роль модели'),
        ),
    ]
