# Generated by Django 6.0.2 on 2026-02-27 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_notes', '0004_chatmessage_prompt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='prompt',
            field=models.CharField(verbose_name='Роль модели'),
        ),
    ]
