# Generated by Django 6.0.2 on 2026-04-29 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_notes', '0005_alter_chatmessage_prompt'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatmessage',
            options={'ordering': ['-time_create'], 'verbose_name': 'Сообщение чата', 'verbose_name_plural': 'Сообщения чата'},
        ),
    ]
