# Generated by Django 6.0.2 on 2026-04-29 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_notes', '0006_alter_chatmessage_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapters',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='chapters',
            name='slug',
            field=models.SlugField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='sections',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='sections',
            name='slug',
            field=models.SlugField(max_length=100, unique=True),
        ),
    ]
